version: '3'

services:
  rabbitmq-node-1:
    image: rabbitmq:3-management
    container_name: rabbitmq-node-1
    hostname: rabbitmq-node-1
    ports:
       - 15672:15672
    volumes:
       - ./data/rabbitmq-node-1:/var/lib/rabbitmq
    environment:
       - RABBITMQ_ERLANG_COOKIE=cluster
       - RABBITMQ_DEFAULT_USER=admin
       - RABBITMQ_DEFAULT_PASS=Admin@123
    networks:
      rabbit-network:
        ipv4_address: 10.5.0.7

  rabbitmq-node-2:
    image: rabbitmq:3-management
    container_name: rabbitmq-node-2
    hostname: rabbitmq-node-2
    ports:
        - 15673:15672
    volumes:
       - ./data/rabbitmq-node-2:/var/lib/rabbitmq
       - ./config/rabbitmq/cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
    environment:
       - RABBITMQ_ERLANG_COOKIE=cluster
    entrypoint: /usr/local/bin/cluster-entrypoint.sh
    restart: on-failure
    depends_on:
       - rabbitmq-node-1
    networks:
      rabbit-network:
        ipv4_address: 10.5.0.8

  rabbitmq-node-3:
    image: rabbitmq:3-management
    container_name: rabbitmq-node-3
    hostname: rabbitmq-node-3
    ports:
       - 15674:15672
    volumes:
       - ./data/rabbitmq-node-3:/var/lib/rabbitmq
       - ./config/rabbitmq/cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
    environment:
       - RABBITMQ_ERLANG_COOKIE=cluster
    entrypoint: /usr/local/bin/cluster-entrypoint.sh
    restart: on-failure
    depends_on:
       - rabbitmq-node-1
    networks:
      rabbit-network:
        ipv4_address: 10.5.0.9

  spring-cloud-stream-rabbitmq-source:
    image: jinternals/spring-cloud-stream-rabbitmq-source
    container_name: spring-cloud-stream-rabbitmq-source
    ports:
        - 8012:8012
    depends_on:
      - rabbitmq-node-1
    networks:
      rabbit-network:
        ipv4_address: 10.5.0.10

  spring-cloud-stream-rabbitmq-sink-0:
    image: jinternals/spring-cloud-stream-rabbitmq-sink
    container_name: spring-cloud-stream-rabbitmq-sink-0
    ports:
        - 8013:8013
    environment:
        - INSTANCE-INDEX=0
    restart: on-failure
    depends_on:
        - rabbitmq-node-1
    networks:
      rabbit-network:
        ipv4_address: 10.5.0.11

  spring-cloud-stream-rabbitmq-sink-1:
    image: jinternals/spring-cloud-stream-rabbitmq-sink
    container_name: spring-cloud-stream-rabbitmq-sink-1
    ports:
        - 8014:8013
    environment:
        - INSTANCE-INDEX=1
    restart: on-failure
    depends_on:
       - rabbitmq-node-2
    networks:
      rabbit-network:
        ipv4_address: 10.5.0.12


  spring-cloud-stream-rabbitmq-sink-2:
    image: jinternals/spring-cloud-stream-rabbitmq-sink
    container_name: spring-cloud-stream-rabbitmq-sink-2
    ports:
        - 8015:8013
    environment:
        - INSTANCE-INDEX=2
    restart: on-failure
    depends_on:
       - rabbitmq-node-3
    networks:
      rabbit-network:
        ipv4_address: 10.5.0.13

  spring-cloud-stream-rabbitmq-sink-3:
    image: jinternals/spring-cloud-stream-rabbitmq-sink
    container_name: spring-cloud-stream-rabbitmq-sink-3
    ports:
        - 8016:8013
    depends_on:
       - rabbitmq-node-3
    restart: on-failure
    environment:
        - INSTANCE-INDEX=3
    networks:
      rabbit-network:
        ipv4_address: 10.5.0.14

  admin-server:
    image: jinternals/admin-server
    container_name: admin-server
    ports:
    - 8585:8585
    networks:
      rabbit-network:
        ipv4_address: 10.5.0.15

networks:
   rabbit-network:
     driver: bridge
     ipam:
      config:
        - subnet: 10.5.0.0/16