server:
  port: 8013

spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka1:9092,kafka2:9093
          autoAddPartitions: true
          minPartitionCount: 4
      bindings:
        demo:
          destination: demo
          group: demo